from pydantic import BaseModel
from typing import Optional
from datetime import datetime

# --- GOAL SCHEMAS ---
class GoalBase(BaseModel):
    thrust_area: str
    title: str
    description: Optional[str] = ""
    uom: str
    target: str
    weightage: int
    is_shared: Optional[bool] = False
    sheet_status: Optional[str] = "Draft"
    actual_achievement: Optional[str] = None
    progress_status: Optional[str] = "Not Started"
    manager_comment: Optional[str] = None
    cycle: Optional[str] = "Phase 1 (Setup)"

class GoalCreate(GoalBase):
    id: str  # We accept the unique ID generated by React

class GoalResponse(GoalBase):
    id: str
    owner_id: Optional[int] = None

    class Config:
        from_attributes = True  # This tells Pydantic to read from our SQLAlchemy models

# --- AUDIT LOG SCHEMAS ---
class AuditLogBase(BaseModel):
    action: str

class AuditLogCreate(AuditLogBase):
    id: str

class AuditLogResponse(AuditLogBase):
    id: str
    timestamp: datetime
    user_id: Optional[int] = None

    class Config:
        from_attributes = True